#############################################################################
# Makefile for building: VideoGet
# Generated by qmake (2.01a) (Qt 4.4.3) on: Tue Apr 16 22:50:10 2013
# Project:  VideoGet.pro
# Template: app
# Command: /opt/DevKit/qtopia4_arm/build_arm/qtopiacore/target/bin/qmake -unix -o Makefile VideoGet.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gcc
CXX           = arm-linux-g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -fno-rtti -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/qws/linux-arm-g++ -I. -I../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/include/QtCore -I../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/include/QtCore -I../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/include/QtNetwork -I../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/include/QtNetwork -I../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/include/QtGui -I../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/include/QtGui -I../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/include -I. -I. -I/usr/local/include/opencv
LINK          = arm-linux-g++
LFLAGS        = -Wl,-rpath,/opt/DevKit/qtopia4_arm/build_arm/sdk/qtopiacore/target/lib
LIBS          = $(SUBLIBS)  -L/opt/DevKit/qtopia4_arm/build_arm/sdk/qtopiacore/target/lib -lQtGui -L/opt/tslib/lib -L/opt/DevKit/qtopia4_arm/build_arm/sdk/qtopiacore/target/lib -lts -lQtNetwork -lQtCore -lm -lrt -ldl -lpthread
INCPATH += -I/usr/local/include/opencv
LIBS += -I/usr/local/include/opencv  -L/usr/local/lib -lcv -lhighgui -lcvaux -lml -lcxcore -lpthread -ldl -lrt

AR            = arm-linux-ar cqs
RANLIB        = arm-linux-ranlib
QMAKE         = /opt/DevKit/qtopia4_arm/build_arm/qtopiacore/target/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		grabvideo.cpp moc_mainwindow.cpp \
		moc_grabvideo.cpp
OBJECTS       = main.o \
		mainwindow.o \
		grabvideo.o \
		moc_mainwindow.o \
		moc_grabvideo.o
DIST          = ../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/qconfig.pri \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/qt_functions.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/qt_config.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/exclusive_builds.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/default_pre.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/release.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/default_post.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/warn_on.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/qt.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/unix/thread.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/moc.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/resources.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/uic.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/yacc.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/lex.prf \
		VideoGet.pro
QMAKE_TARGET  = VideoGet
DESTDIR       = 
TARGET        = VideoGet

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: VideoGet.pro  ../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/qws/linux-arm-g++/qmake.conf ../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/qconfig.pri \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/qt_functions.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/qt_config.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/exclusive_builds.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/default_pre.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/release.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/default_post.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/warn_on.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/qt.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/unix/thread.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/moc.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/resources.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/uic.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/yacc.prf \
		../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/lex.prf \
		/opt/DevKit/qtopia4_arm/build_arm/sdk/qtopiacore/target/lib/libQtGui.prl \
		/opt/DevKit/qtopia4_arm/build_arm/sdk/qtopiacore/target/lib/libQtNetwork.prl \
		/opt/DevKit/qtopia4_arm/build_arm/sdk/qtopiacore/target/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile VideoGet.pro
../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/qconfig.pri:
../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/qt_functions.prf:
../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/qt_config.prf:
../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/exclusive_builds.prf:
../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/default_pre.prf:
../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/release.prf:
../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/default_post.prf:
../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/warn_on.prf:
../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/qt.prf:
../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/unix/thread.prf:
../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/moc.prf:
../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/resources.prf:
../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/uic.prf:
../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/yacc.prf:
../../../qtopia4_arm/build_arm/sdk/qtopiacore/target/mkspecs/features/lex.prf:
/opt/DevKit/qtopia4_arm/build_arm/sdk/qtopiacore/target/lib/libQtGui.prl:
/opt/DevKit/qtopia4_arm/build_arm/sdk/qtopiacore/target/lib/libQtNetwork.prl:
/opt/DevKit/qtopia4_arm/build_arm/sdk/qtopiacore/target/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile VideoGet.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/VideoGet1.0.0 || $(MKDIR) .tmp/VideoGet1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/VideoGet1.0.0/ && $(COPY_FILE) --parents mainwindow.h grabvideo.h .tmp/VideoGet1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp grabvideo.cpp .tmp/VideoGet1.0.0/ && (cd `dirname .tmp/VideoGet1.0.0` && $(TAR) VideoGet1.0.0.tar VideoGet1.0.0 && $(COMPRESS) VideoGet1.0.0.tar) && $(MOVE) `dirname .tmp/VideoGet1.0.0`/VideoGet1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/VideoGet1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_grabvideo.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_grabvideo.cpp
moc_mainwindow.cpp: grabvideo.h \
		mainwindow.h
	/opt/DevKit/qtopia4_arm/build_arm/sdk/qtopiacore/target/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_grabvideo.cpp: grabvideo.h
	/opt/DevKit/qtopia4_arm/build_arm/sdk/qtopiacore/target/bin/moc $(DEFINES) $(INCPATH) grabvideo.h -o moc_grabvideo.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		grabvideo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		grabvideo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

grabvideo.o: grabvideo.cpp grabvideo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o grabvideo.o grabvideo.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_grabvideo.o: moc_grabvideo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_grabvideo.o moc_grabvideo.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

